### ISSUE TITLE
Questions about the details of NuTime

### ISSUE THREAD

**Issue by jexterliangsufe** [chenguolin/NuTime#1]
Greate works! 
I read the paper and your latest released codes. It may solve the bottleneck in my application. Here I have 2 questions. 
1) Have you considered using overlapping windows in Patchify module like PatchTST did? 
2) In your paper, threre is little content mentioned about `loc_w`(i.e. the weights of loacations). What's the purpose of the locations? 
Thank you in advance for your reply~

**Comment by chenguolin** [comment]
Hi @jexterliangsufe,

Thanks for your interest in our project and sorry for the late reply.

1. No, actually we started this project before PatchTST, and we want to keep everything simple, so we didn't use overlapping windows. Feel free to try by just modifying the kernel size and stride of the tokenization convolution layer.

2. Please refer to Appendix C.  It is motivated by an insight that the input scalar $x$ should be embedded by the basic building block (i.e., linear + LayerNorm) which has a $k$ that shares a comparable numerical scale.

**Comment by jexterliangsufe** [comment]
Thank you for your kind reply!
